platforms:
  - type: GKE
    launch_stage: GA
    detections:
      - characteristic_metric:
          metric_type: prometheus.googleapis.com/activemq_connections_total/gauge
    exporter_metadata:
      name: ActiveMQ Prometheus Exporter
      doc_url: https://github.com/bitnami/containers/tree/main/bitnami/jmx-exporter#readme
      minimum_supported_version: "0.17.0"
    default_metrics:
      - name: prometheus.googleapis.com/activemq_connections_total/gauge
        prometheus_name: activemq_connections_total
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_consumer_total/counter
        prometheus_name: activemq_consumer_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_producer_total/counter
        prometheus_name: activemq_producer_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_memory_usage_ratio/gauge
        prometheus_name: activemq_memory_usage_ratio
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_store_usage_ratio/gauge
        prometheus_name: activemq_store_usage_ratio
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_temp_usage_ratio/gauge
        prometheus_name: activemq_temp_usage_ratio
        kind: GAUGE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_topic_average_blocked_time/unknown:counter
        prometheus_name: activemq_topic_average_blocked_time
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_message_total/counter
        prometheus_name: activemq_message_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_topic_expired_count/unknown:counter
        prometheus_name: activemq_topic_expired_count
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_enqueue_total/counter
        prometheus_name: activemq_enqueue_total
        kind: CUMULATIVE
        value_type: DOUBLE
      - name: prometheus.googleapis.com/activemq_dequeue_total/counter
        prometheus_name: activemq_dequeue_total
        kind: CUMULATIVE
        value_type: DOUBLE
    install_documentation_url: https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/activemq
